name: other updates

on:
  schedule:
    # 3시간마다 실행 (UTC 기준)
    - cron: "0 */3 * * *"
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Market Weather Update
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_MODEL_NAME: ${{ vars.GEMINI_MODEL_NAME }}
        run: python stockWeather.py

      - name: Run Money Flow Update
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_MODEL_NAME: ${{ vars.GEMINI_MODEL_NAME }}
        run: python moneyFlow.py
      - name: Run Currency Desk Update
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_MODEL_NAME: ${{ vars.GEMINI_MODEL_NAME }}
        run: python currencyDesk.py
